// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCCI59imPz6l-9aTeEtr2wIbRl93LA2Hc',
    appId: '1:566320658572:web:dc9fc11a2346b315d063a9',
    messagingSenderId: '566320658572',
    projectId: 'ac-reminder-app',
    authDomain: 'ac-reminder-app.firebaseapp.com',
    storageBucket: 'ac-reminder-app.appspot.com',
    measurementId: 'G-120J28J409',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkKYWJ_5Vyz0OAx50g0pCk-RbnpSzl9XE',
    appId: '1:566320658572:android:af90010f073a1121d063a9',
    messagingSenderId: '566320658572',
    projectId: 'ac-reminder-app',
    storageBucket: 'ac-reminder-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMtBQDRl3uFpjnPrFcU2raxEkN8AKj4UA',
    appId: '1:566320658572:ios:0681678db7b0a264d063a9',
    messagingSenderId: '566320658572',
    projectId: 'ac-reminder-app',
    storageBucket: 'ac-reminder-app.appspot.com',
    iosBundleId: 'com.example.acReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMtBQDRl3uFpjnPrFcU2raxEkN8AKj4UA',
    appId: '1:566320658572:ios:0681678db7b0a264d063a9',
    messagingSenderId: '566320658572',
    projectId: 'ac-reminder-app',
    storageBucket: 'ac-reminder-app.appspot.com',
    iosBundleId: 'com.example.acReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCCI59imPz6l-9aTeEtr2wIbRl93LA2Hc',
    appId: '1:566320658572:web:ff78a7f3405bc785d063a9',
    messagingSenderId: '566320658572',
    projectId: 'ac-reminder-app',
    authDomain: 'ac-reminder-app.firebaseapp.com',
    storageBucket: 'ac-reminder-app.appspot.com',
    measurementId: 'G-QWFRJW20YM',
  );
}
